# The python packages necessary to run Project Image_Similarity_in_Marvel_MCU
#
# To create the conda environment:
# $ conda env create -f environment.yml
# 
# To update the conda environment:
# $ conda env update -f environment.yml
# 
# To register the conda environment in Jupyter:
# $ conda activate mcu
# $ python -m ipykernel install --user --name mcu
#
# run: conda env remove -n mcu
# 

name: mcu
# in order of priority: lowest (top) to highest (bottom)
channels:
  - conda-forge
  - defaults
dependencies:
- cython # wrapping Python around C. C is fast.
- h5py # for the ubiquitous HDF5 file format. (h5py==2.7.0)
- keras # deep learning library (keras==2.0.2)
- pandas # working with tabulated data  (pandas==0.25.1)
- pillow # classic fork of Python Imaging Library (Pillow==6.1.0)
- pip # THE python package manager
- python==3.7.4 # the latest python release running on dev machine
- matplotlib>=3.0.1 # classic plotting  (matplotlib==3.1.1)
- numpy # essential math and matrix operations (numpy==1.16.5)
- scikit-image # image processing https://scikit-image.org/docs/stable/install.html
- 
- 
- openpyxl==3.0.2
- 
- imagehash
- tensorflow # deep learning backend for keras
- tqdm # popular progress bar for jupyter
#- scikit-learn # machine learning
#- scipy # numerical methods
- jupyter # great tool for any python project.
- nb_conda_kernels
- ipykernel
- pip:
  - keras-tqdm # tqdm for keras
  - tensorflow-gpu # deep learning on GPU hardware
  - tensorflow-gpu==1.12.1
  - azure-storage-blob>=1.5.0, <=2.1.0   # doc: https://azure-storage.readthedocs.io - this will go to versions prior to v12 update
  #- argparse


# the `nb_conda_kernels` and `ipykernel` packages are installed so that we
# can use Jupyter Notebooks with this environment as a kernel

# more enhancements here: https://github.com/microsoft/AKSDeploymentTutorialAML/blob/master/.ci/azure-pipelines.yml
