# The python packages necessary to run Project Image_Similarity_in_Marvel_MCU
#
# Install: conda env create -f environment.yml
# Update:  conda env update -f environment.yml --prune
# Remove: conda env remove -n poe
#

name: mcu
# in order of priority: lowest (top) to highest (bottom)
channels:
  - default
  - conda-forge
  - pytorch
  - fastai
  dependencies:
    - cython # wrapping Python around C. C is fast.
    - fastai
    - h5py==2.7.0 # for the ubiquitous HDF5 file format. (h5py==2.7.0)
    - keras==2.0.2 # deep learning library (keras==2.0.2)
    - keras-applications==1.0.8 # pre-trained weights architectures for VGG* ResNet*
    - keras-preprocessing==1.1.0 # data preprocessing and data augmentation module
    - pandas==0.25.1 # working with tabulated data  (pandas==0.25.1)
    - pillow==6.1.0 # classic fork of Python Imaging Library (Pillow==6.1.0)
    - pip # THE python package manager
    - python==3.7.4 # the latest python release running on dev machine
    - matplotlib==3.1.1 # classic plotting  (matplotlib==3.1.1) or >=3.0.1
    - numpy==1.16.5 # essential math and matrix operations
    - scikit-image==0.15.0 # image processing https://scikit-image.org/docs/stable/install.html
    - imageio=2.5.0
    - openpyxl==3.0.2
    - imagehash==4.0
    - tensorflow # deep learning backend for keras
    - tqdm # popular progress bar for jupyter
    #- scikit-learn # machine learning
    - scipy==1.3.1 # numerical methods
    - jupyter # great tool for any python project.
    - nb_conda_kernels
    - ipykernel
    - pip:
      - keras-tqdm # tqdm for keras
      - tensorflow-gpu==1.12.1 # deep learning on GPU hardware
      - azure-storage-blob>=1.5.0, <=2.1.0   # doc: https://azure-storage.readthedocs.io - this will go to versions prior to v12 update
      #- argparse
    
    
    # the `nb_conda_kernels` and `ipykernel` packages are installed so that we
    # can use Jupyter Notebooks with this environment as a kernel
    
    # more enhancements here: https://github.com/microsoft/AKSDeploymentTutorialAML/blob/master/.ci/azure-pipelines.yml
